### ISSUE TITLE
Remaining number of NFTs per drop

### ISSUE THREAD

**Issue by gokaiorg** [ElvenTools/elven-tools-dapp#1]
When a set-drop has been made it would be nice to have the number of NFTs available for the active drop.

Also, if we mint a certain number of NFTs and change the tokens limit per wallet we get a negative number.

<img width="374" alt="Capture d’écran 2022-04-14 à 15 29 08" src="https://user-images.githubusercontent.com/8545464/163345990-103537f0-fe55-4810-a6f6-897ca3964d64.png">

**Comment by juliancwirko** [comment]
You would need to keep the config in sync with your smart contract settings for drops. This one: https://github.com/ElvenTools/elven-tools-dapp/blob/main/config/nftSmartContract.ts. You would need to set the `isDropActive` to true, set the number of tokens per drop, and then redeploy the app. This is because it saves a lot of traffic and API calls, but it will be served as an option in the future. By default, all will be queried on a smart contract, and when the config is provided, it will use the static settings. I'll add detailed docs soon.

**Comment by gokaiorg** [comment]
It's working as well, thank you 😊 
<img width="383" alt="Capture d’écran 2022-04-15 à 13 28 42" src="https://user-images.githubusercontent.com/8545464/163530775-700dc467-159e-457b-bd23-a1a2a5bd8a40.png">
