### ISSUE TITLE
Add profil section

### ISSUE THREAD

**Issue by theejkb** [ElvenTools/elven-tools-dapp#10]
Add a profil section
Show all NFT on the profil section

**Comment by theejkb** [comment]
Enable user to change their profil picture (or take the profil picture from maiar mobile)

**Comment by juliancwirko** [comment]
Good idea, thanks, added to TODO.

**Comment by theejkb** [comment]
I'm actually working on the front-end part, I'll do a pull request

**Comment by juliancwirko** [comment]
Cool, I think the first part makes sense (list of NFTs) because it doesn't require the backend logic. The dapp doesn't assume there will be a backend logic, at least for now. So, for the avatar, if there is a public API to get the avatar from the Maiar wallet setup, it could also be a good addition, but all stuff that requires a backend would need to wait for now.
